<script lang="ts">
  import { formatBigNumber } from "$lib/db/helpers";
  import { filterTransactionsByPeriod, getTotalAmount } from "$lib/utils/tx";
  import Icon from "../ui/Icon.svelte";
  import Tooltip from "../ui/Tooltip.svelte";

  export let transactions: any;
  export let period: "week" | "month" | "year";

  let totalBalance = 0;
  let income = 0;
  let expenses = 0;
  let aiSummary = ""; // New variable to hold AI summary

  $: {
    const filteredTransactions = filterTransactionsByPeriod(
      transactions,
      period
    );

    const data = getTotalAmount(filteredTransactions);

    totalBalance = data.totalBalance;
    income = data.income;
    expenses = data.expenses;
  }

  function generateAISummary() {
    aiSummary = "";
    alert("This feature is not implemented yet");
  }
</script>

<div>
  <p>Total balance</p>
  <p class="text-2xl font-bold">
    {formatBigNumber(totalBalance, "USD", totalBalance < 0 ? true : false)}
  </p>
</div>
<div class="flex justify-between w-full">
  <div>
    <p class="inline-flex gap-2.5">
      <Icon
        id="streamline-money-graph-arrow-increase-ascend-growth-up-arrow-stats-graph-right-grow"
        class="w-4 h-4 inline-block text-green-500"
      />
      Income
    </p>
    <p class="text-2xl font-bold">
      {formatBigNumber(income, "USD", false)}
    </p>
  </div>
  <div>
    <p class="inline-flex gap-2.5">
      <Icon
        id="streamline-money-graph-arrow-decrease-down-stats-graph-descend-right-arrow"
        class="w-4 h-4 inline-block text-red-500"
      />
      Expenses
    </p>
    <p class="text-2xl font-bold text-right">
      {formatBigNumber(expenses, "USD", true)}
    </p>
  </div>
</div>
{#if !aiSummary}
  <button class="mt-4 text-primary underline" on:click={generateAISummary}>
    Generate AI summary
  </button>
{:else}
  <div>
    <p>
      Summary <Tooltip
        message="Generated by AI - can be inaccurate"
        icon="material-symbols-warning-rounded"
      />
    </p>
    <p>
      {aiSummary}
    </p>
  </div>
{/if}
